---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "appwrite.fullname" $ }}-smtp-env"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
type: Opaque
data:
  _APP_SMTP_USERNAME: {{ .Values.smtp.user | b64enc | quote }}
  _APP_SMTP_PASSWORD: {{ .Values.smtp.pass | b64enc | quote }}
